### ISSUE TITLE
Potential bug when reopening datastream after it has closed already.

### ISSUE THREAD

**Issue by ehpor** [spacetelescope/catkit2#113]
From hicat-package2 CI:
```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/catkit2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/share/miniconda/envs/catkit2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/hicat-package2/hicat-package2/hicat-package2/hicat2/conftest.py", line 27, in run_testbed
    testbed = Testbed(port, is_simulated, config)
  File "/home/runner/work/hicat-package2/hicat-package2/catkit2/catkit2/testbed/testbed.py", line 179, in __init__
    self.services[service_id] = ServiceReference(service_id, service_type, ServiceState.CLOSED, dependencies)
  File "/home/runner/work/hicat-package2/hicat-package2/catkit2/catkit2/testbed/testbed.py", line 50, in __init__
    self.state_stream = DataStream.create('state', service_id, 'int8', [1], 20)
RuntimeError: Something went wrong while creating shared memory.
```

We are not outputing any details about this error, so there's no way to debug this.

**Comment by lanemeier7** [comment]
I am getting this error intermittently with my CI system. Sometimes when test cases are run I get the "Something went wrong while creating shared memory." bubbling up.

```
self = <catkit2.testbed.testbed_proxy.TestbedProxy object at 0x000001DDE7186CA8>
item = 'accufiz_interferometer'
    def __getattr__(self, item):
        '''Get the ServiceProxy named after the attribute.
    
        This acts as a shortcut for :func:`~catkit2.testbed.TestbedProxy.get_service`.
    
        Parameters
        ----------
        item : string
            The identifier for the service for which to return the ServiceProxy.
    
        Returns
        -------
        ServiceProxy or derived class object.
            A ServiceProxy for the named service.
        '''
        try:
            service = self.get_service(item)
    
            # Remember the service for next time.
            setattr(self, item, service)
    
            return service
        except Exception as e:
>           raise AttributeError(str(e))
E           AttributeError: Something went wrong while opening shared memory.
c:\catkit2\catkit2\testbed\testbed_proxy.py:66: AttributeError

```
